### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by sxzrmn** [Ilikemyhome/Week7#2]
Added task 3 to Sprint 3

**Comment by sxzrmn** [comment]
Added new labels to Sprint 3 and deleted the default labels.

**Comment by sxzrmn** [comment]
I altered the html code for the Great Outdoors website and pushed it to the main repository, but for some reason I'm unable to push the changes through to the branch "Team1".  What am I missing?

**Comment by Ilikemyhome** [comment]
added some css on the table of contents making
